import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
    faCheckSquare,
    faCoffee,
    faFileAlt,
    faStar,
    faSearch,
    faUser,
    faTrashAlt,
    faHashtag,
    faCircle,
    faAngleDown,
    faPlus,
    faPlusCircle,
    faEllipsisH,
    faEllipsisV,
    faCheckCircle,
    faTimesCircle,
    faBold,
    faItalic,
    faUnderline,
    faStrikethrough,
    faHeading,
    faParagraph,
    faListOl,
    faListUl,
    faCode,
    faCodeBranch,
    faImage,
    faCheck,
    faQuoteRight,
} from '@fortawesome/free-solid-svg-icons';
import { faEdit } from '@fortawesome/free-regular-svg-icons';

library.add(
    fab,
    faCheckSquare,
    faCoffee,
    faFileAlt,
    faStar,
    faSearch,
    faUser,
    faTrashAlt,
    faHashtag,
    faEdit,
    faCircle,
    faAngleDown,
    faPlus,
    faPlusCircle,
    faEllipsisH,
    faEllipsisV,
    faCheckCircle,
    faTimesCircle,
    faBold,
    faItalic,
    faUnderline,
    faStrikethrough,
    faHeading,
    faParagraph,
    faListOl,
    faListUl,
    faCode,
    faCodeBranch,
    faImage,
    faCheck,
    faQuoteRight,
);
